version: '3'

services:

  django:
    image: hgmachine/django-web-01
    volumes: ["./learning_log_project:/workspace"]
    ports:   ["8181:8181", "8000:8000"]
    command: --auth hgmachine:ued13sa1605
    depends_on: ["db"]
    networks: ["my_net"]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: log27hgdata
    volumes: ["./postdb/database:/var/lib/postgresql/data"]
    ports: ["5432"]
    networks: ["my_net"]

networks:
   my_net:
